version: "3.8"
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
